apiVersion: batch/v1
kind: CronJob
metadata:
  name: harness-agent-agent-upgrader
  namespace: harness-gitops
spec:
  schedule: "0 */4 * * *"
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 20
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: harness-agent-agent-upgrader
          containers:
              - name: upgrader
                image: harness/upgrader:latest
                imagePullPolicy: Always
                env:
                  - name: POD_NAMESPACE
                    valueFrom:
                      fieldRef:
                        fieldPath: metadata.namespace
                volumeMounts:
                  - name: config-volume
                    mountPath: /etc/config
                  - name: certvol
                    mountPath: /tmp/ca.bundle
                    subPath: ca.bundle
          volumes:
            - name: config-volume
              configMap:
                name: harness-agent-agent-upgrader
            - name: certvol
              secret:
                secretName: harness-agent-agent-ca
                optional: true
                items:
                - key: ca.bundle
                  path: ca.bundle
          restartPolicy: Never
---