apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/name: argocd-secret
    app.kubernetes.io/part-of: argocd
  name: argocd-secret
  namespace: harness-gitops
type: Opaque

---

apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/name: gitops-agent-secret
    app.kubernetes.io/part-of: argocd
  name: harness-agent-agent
  namespace: harness-gitops
type: Opaque
stringData:
  GITOPS_AGENT_TOKEN: |
    LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFdmdJQkFEQU5CZ2txaGtpRzl3MEJBUUVGQUFTQ0JLZ3dnZ1NrQWdFQUFvSUJBUUM4dUpFZVp5NFo2MGI5CkhaV3FPQzFhV1FJb0tsSVNjUlFVUkhuOUU3TU91WmNldDdmVnlNdDlrSGZZUlMyaUpnRFNxRWRtcUVGVUFYaHYKdzZ1N1BzTXQ1SWJIVWhWb2FvQWdWUGVtbXQza2YvM0Z4SXVLSUJ0czJGSFFkQlhKRUUrbFk0RHZrdk4vQlhKaQpyM2NWT0J4clkzVCthdHUydFo1S3VvekVrZ0dHL1JycFJHUnhuMCtuQ2lnTTNvQkJTYmlma2FtRENPWkJ5d1JJCkgyYzNpUzlaZlZ1VEp4ZVRPZHNITTR5ZTI4RzJTNnIwWWg5MGJDYlpwbUFVQlNPeDQ3dGxOSlNlK2ZwdnlTWTEKdld1RUhsUThJTzdwZmJFamxOYXc0RmRId2haa0tBRWRnZHo1cVNrVnNvcElwb1h0ekdoZ0NHWUxwcUh5K29kTwpnOUlzY3BOdkFnTUJBQUVDZ2dFQWU1ZkVNazBRZkJrQm5MTExXWGNBL0xKZUh6L1lFQXZPUXBlMTdIQUNUQnB2ClJjYTd0bDZTSmVGL0d6dnk3c1pFczdGUlVZSFBodHlQcTJKU0RZYkUvRUUxbzBPMmtYTnVCYjZma1pUS3pPS2wKcCtkWUcxVjdvSVRxejhHMm9yN3o2alNJTkYzZzZjYi9hbkhQWXk0a0xwQXNCcEtrNGJ0L3R5RUZINWNmT085WQpZMm53bURuVjNPSTFnbFlzRGZiYVUrSnFrRG1NV1FxNExON3AwZzBDb1VRanJpdnEvMW5vUjlnMko1bTd6Y014CkQwS2xONnJITkJQREVlYzV2VTFGa01ueDE5SEdoUGNEbVhwOE1vVENhUnQvZTVsR3VBRGZYTDdxNmViRnFKYmcKVEtSWTFOYTlHSEpBcHkydnBkMjgzLzI4RTRjdmIycGJFK0QweFczV3dRS0JnUUR5MjREb21acUQ1WUFVa1dYZQp6ZjQ3L1p3NmNiOFVaTFhhR0JFbWhuWGRpSGVOY21SYXhCTDZiOWx0R1BaeldzSGYza0ZwaUE4SkxEVUlUZGQ4CjlFOGRpQytCTEhJUm9lVlVjZWRQc3dRQ2d6ZGZuVzdmdi9ReFkvQmRTZnhRRThSSEw4cWFXK2tZRFhLZEhUcFkKMnY2NUNuWEVDNlg1MUI0dUtodjVQaFFacXdLQmdRREc3eEZobGpQemp6S2xGaVdReGNlWW9FS21FYkY3R1dieApwVmxGYU85UU5GUVVLWXIvV3IzYTV3azFJOHA0RUtFSjBicElyNTdVR3U5UjZ6MlJKVVpZSFBhTjdQTklKbExhClRhZFAvUy8wQlB3MnBSZTZKTDFIalN5Z1g5NDFUb3lkT3RpVTMyazE3QTJVSzJKL0gvMGxpc0xsMkhsRVRqdVQKYWpEcjdwZVJUUUtCZ1FESW1oUFREZjRaOE5wcEl1allyNkxPL3QrclR3V2MzTXR4eU90eHZTTml5RFNvZTlMMQpQbnpHck5rV1NzWlg1cUc2UDZZY2U2eWYwUXBGUDdjOW1iZzRGcVBXdVZYSHhzamRoZkNoWHFkelE5dmJlUGw2CmpONHlaZkRIdmpOU0dlSEpRMnJCTWlaS0hlR01jZlllSzFhNGxqRk1yS3Ard0gzbGVCYi9QQTN5WFFLQmdDZVAKbVd4SHU1TWZFaHBFZWpuOUt3Rk9OWkxqQitHTUhxM0ZqU2hCZ3YzM09oVThZYmtBYWFzanNQQVJhdzFQZVVjRApuMEVmTTczSWtYbEFCK0ZhZ1UrNmlzbVVxcGpaampaOXBOMUNZNHZxaGVHMEdURGFaNDNZSkZ6TVU5dFVBS0N2CitDdzY5YWhVaGlyR0tmTlFBRDY4QnFCQTJYVGMvZm9GN3k2c0p4WXRBb0dCQUpySlk4bGl2YWZtZ3VHRC9ySzMKcXMzQ2VJVXNxbUVLK2NTemc1OFFES0p5eTZHVjI3eUxxVFhnbkoyeThtM3lZVHlWcG8vaDZOU3Fyd1BCcmkrYwpEbEZwOE9MYlBHL1B4ZndYdUtoSUhaRzhZY2xCVWxHNER2MDF2bDUrNXVra2I2QW5LZTBBa0J6cVE2ZlMrN0FkCkxMczkrQnBwTkNCQ3Z2cWNCY29HYkxUZwotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
---

